// AUTHENTICATION
export const SIGN_IN          = 'SIGN_IN';
export const SIGN_OUT         = 'SIGN_OUT';

// STREAMS
export const CREATE_STREAM_REQUEST  = 'CREATE_STREAM_REQUEST';
export const CREATE_STREAM_SUCCESS  = 'CREATE_STREAM_SUCCESS';
export const FETCH_STREAMS_REQUEST  = 'FETCH_STREAMS_REQUEST';
export const FETCH_STREAMS_SUCCESS  = 'FETCH_STREAMS_SUCCESS';
export const FETCH_STREAM_REQUEST   = 'FETCH_STREAM_REQUEST';
export const FETCH_STREAM_SUCCESS   = 'FETCH_STREAM_SUCCESS';
export const DELETE_STREAM          = 'DELETE_STREAM';
export const UPDATE_STREAM_REQUEST  = 'UPDATE_STREAM_REQUEST';
export const UPDATE_STREAM_SUCCESS  = 'UPDATE_STREAM_SUCCESS';
